baseURL: https://ruoxuanbai-lbs-2021.netlify.app/
languageCode: en-us
title: Portfolio website for Ruoxuan Bai 
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Know more about me
    subtitle: |-
     A Finance Major Student at London Business School
     And Someone with Passion for Everything in Life.
    title: Welcome to Ruoxuan Bai's website. Very nice meeting you!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 21 King's Street
        title: Flat 201
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: rbai.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (647) 9790629
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Ruoxuan Bai - London Business School, 2021
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: twitter
      #  label:
       # url:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/ruoxuan.bai/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/bai_ruoxuan/
      - icon: fa-github
        label: GitHub
        url: https://github.com/RuoxuanBai/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/roxannebai/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#- name: Generic Blog
# url: blogs/ipsum
#- name: Elements
# url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: A year when I meet with everything
        title: London Business School
        url: https://www.london.edu/masters-degrees/masters-in-financial-analysis/
      - image: pic08.jpeg
        subtitle: A professional resume of a future investment banker
        title: Resume
        url: resume.pdf
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Homework 1
        url: Homework1.html
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Homework 2
        url: homework2.html
      - image: milan.jpeg
        subtitle: A analytical project for AirBnB in Milan 
        title: AirBnB Group Project
        url: group_project.html
      - image: pic05.jpg
        subtitle:  
        title: Group Presentation
        url: AirBnB.pptx
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
